- go.sum
> update go.sum for compiling problems

- miner/multiminer.go
- node/impl/miner.go
- node/modules/dtypes/miner.go
- node/modules/minermanage/auth/auth.go
venus-auth commits after f44639e14, break the api's compatibility.
venus-miner should satisfy this change.
> satisfy venus-auth after 

- node/modules/minermanage/auth/auth.go
> fix: command 'address update' haven't save addresses

- Makefile
- dockerfile
change to build docker image from local repo rather than from git chech out
pass env var BUILD_DOCKER_PROXY to docker when make image
> fix: venus-miner : change to  build docker image from local repo 

- dockerfile
fix https://github.com/filecoin-project/venus/issues/4999
update dependencies of ddl from base docker image
> fix #4999 : venus-miner : update dependencies of ddl

- miner/api.go
- miner/miningmgr.go
- miner/multiminer.go
- node/builder.go
- node/modules/slashfilter/api.go
- node/modules/slashfilter/local.go
- node/modules/slashfilter/mysql.go
resolve filecoin-project/venus#4919
> record more minning info

- docker/script/compose.sh
fix https://github.com/filecoin-project/venus/issues/5045
remove nettype arg in compose script
> fix: ignore nettype arg in docker compoes script

- cli/cmd.go
- cmd/main.go
resolve: https://github.com/filecoin-project/venus/issues/4964
> fix: rename miner-repo to repo

- .github/workflows/tag-workflow.yml
only trigger auto publish on PR is merged
原因及方案说明: https://github.com/filecoin-project/venus/issues/5090
> chore: git action: only trigger auto publish on PR merged

- cmd/main.go
- cmd/run.go
- docs/zh/config-desc.md
- go.mod
- go.sum
- lib/metrics/expoter.go
- lib/metrics/metrics.go
- miner/multiminer.go
- node/config/def.go
resolve filecoin-project/venus#4960
> 实现metrics监控指标及配置

- miner/multiminer.go
修复`Miner.mine`在`stop`后可能无法退出的问题. 
fixes: https://github.com/filecoin-project/venus/issues/5166
> fix: mine may stuck in infinity loop after calling stop

- node/modules/core.go
- node/repo/fsrepo.go
- node/repo/repo_test.go
- types/keystore.go
empty
refactor: 
remove local definition of `KeyType`, use the one defined in venus-shared/ 移除本地重复定义的`KeyType` , 使用venus-shared中的替代.
> refactor: remove local definition of `KeyType`, use the one defined in venus-shared

- miner/multiminer.go
no
fix: 'winPosts' race access problem.
> fix: 'winPosts' was write parallelly, without syncing.

- .gitignore
- Makefile
- docker/script/init.sh
- dockerfile
involve https://github.com/filecoin-project/venus/issues/5240
- devide mod download and build when building docker
- set default test tag to image
- use unify dockerfile
> feat: rm dockerfile

- cmd/run.go
involve https://github.com/filecoin-project/venus/issues/5247
- add wait loop which run util height of chain not zero
> feat: wait util height of chain not zero

- docs/en/config-desc.md
- docs/en/metrics.md
- docs/zh/metrics.md
- lib/metrics/metrics.go
- miner/multiminer.go
> feat: metrics for mining failed / 出块失败的统计指标

- miner/warmup.go
> fix: Warmup increases the sectorKey parameter / warmup 调用证明接口时增加SectorKey参数

- build/version.go
> chore: upgrade go version to 1.18

- .circleci/config.yml
- Makefile
- README.md
- go.mod
- go.sum
> chore: upgrade go version to 1.18.1

- miner/miningmgr.go
close filecoin-project/venus#5419
> fix: close of closed channel for signer

- .circleci/config.yml
- lib/journal/alerting/alerts_test.go
- lib/journal/fsjournal/fs_test.go
- lib/journal/registry_test.go
- miner/miner_test.go
- node/config/apiinfo_test.go
- node/modules/slashfilter/slashfilter_test.go
- node/repo/fsrepo.go
- node/repo/fsrepo_test.go
- node/repo/repo_test.go
closes https://github.com/filecoin-project/venus/issues/5413
增加STM注解.
> feat: adding stm annotations/增加STM注解

- miner/multiminer.go
> fix: connect gateway in sign request

- go.mod
- go.sum
- miner/miner_test.go
- miner/minerwpp.go
- miner/miningmgr.go
- miner/multiminer.go
- miner/warmup.go
- node/builder.go
- node/modules/miner-manager/api.go
- node/modules/miner-manager/auth_manager.go
- node/modules/miner-manager/mock/miner_manager.go
- node/modules/miner.go
- node/modules/slashfilter/slashfilter.go
- types/miner.go
close filecoin-project/venus#5415
> Feat: add mining switch / 增加出块控制开关

- .circleci/config.yml
- miner/miningmgr.go
- miner/multiminer.go
> refactor: optimize count winner logical/重构优化countwinner逻辑

- go.mod
- go.sum
- miner/multiminer.go
- node/modules/miner-manager/auth_manager.go
> fix: upgrade venus-auth ver for ListUsersWithMiners API

- cmd/run.go
> feat: remote jwt token

- docs/zh/metrics.md
- lib/metrics/metrics.go
https://github.com/filecoin-project/venus/issues/5488
> chore: add rpc metrics

- .circleci/config.yml
> chore(CI): permission denied exit for sh script

- api/api_common.go
- api/client/gateway_client.go
- api/docgen/example.go
- api/proxy_gen.go
- build/version.go
- cmd/run.go
- go.mod
- go.sum
- miner/miner_test.go
- miner/multiminer.go
- miner/util.go
- node/config/gatewaydef.go
- node/impl/common/common.go
> feat: upgrade sign logic

- go.mod
- go.sum
> chore: upgrade venus-related ref version

- miner/warmup.go
关联pr: https://github.com/filecoin-project/lotus/pull/9843/files#diff-9c0af2fc7ed779fda921ab8df8c1daa147d1a6ec3f94395e6167997caaf45625
增加对sectorinfo是否nil的检查
> chore: add nil check for sector info

- go.mod
- go.sum
> chore: upgrade venus-related ref version to 1.9.0

- api/api_miner.go
- api/proxy_gen.go
- cmd/run.go
- go.mod
- go.sum
- node/builder.go
- node/impl/miner.go
- node/modules/miner-manager/auth_manager.go
ref  https://github.com/filecoin-project/venus/issues/5384
> Feat/tanlang/user data isolation / 增加用户数据隔离

- node/modules/slashfilter/slashfilter.go
> feat: mysql table migrate for miner_blocks

- node/config/def.go
ref filecoin-project/venus#5804
> fix: config check

- miner/multiminer.go
close
在链同步较慢时，会设置等待base+computeproof的时间超过30s，这样理论上可以规避部分孤块，但是链分叉判断哪里有可能收到的已经是新周期的，所以在判断时只对同周期内判断
> opt: chain-forked check

- build/version.go
- docs/zh/CHANGELOG.md
- miner/multiminer.go
> Chore/lt/pick 181 to v1.10

- miner/multiminer.go
> opt: set the select messages timeout

- build/version.go
- docs/zh/CHANGELOG.md
- miner/multiminer.go
> Chore/lt pick pr184 to 1.10

- miner/miner_test.go
close
- 分叉后链的前进逻辑更加符合实际场景
- 之前逻辑存在个问题，如果分叉前head包含的区块比较多(5),构造新的head包含区块较少(1),这个时候给予构造head创建的区块重量小于head的重量,导致链没法前进.
> fix(CI): keep chain going funcs

- build/version.go
- docs/zh/CHANGELOG.md
- miner/miner_test.go
- miner/multiminer.go
- node/modules/miner-manager/auth_manager.go
> Feat: cherry-pick 187,188 :update base correctly

- Makefile
- build/version.go
- docs/zh/CHANGELOG.md
- go.mod
- go.sum
> Pre/v1.11 / 合并预发布分支

- build/version.go
- docs/zh/CHANGELOG.md
- go.mod
- go.sum
> chore: bump up version to v1.11.0

- miner/multiminer.go
- node/config/def.go
> feat: message pool select delay secs to configure

- Makefile
- build/version.go
- docs/zh/CHANGELOG.md
- go.mod
- go.sum
> chore: merge Release/v1.11 into master

- miner/multiminer.go
close filecoin-project/venus#6007
> fix: Correctly handle null round

- miner/miner_test.go
> fix: data race of mockChain

- scripts/build-bundle.sh
- scripts/publish-release.sh
> fix: build and publish bundle script

- cli/cmd.go
close filecoin-project/venus#6033
> fix: cmds compatible old repo

- lib/journal/fsjournal/fs_test.go
> fix: replace ioutil with os

- .circleci/config.yml
- build/version.go
- docs/zh/CHANGELOG.md
- go.mod
- go.sum
- lib/journal/fsjournal/fs_test.go
close https://github.com/filecoin-project/venus/issues/6042
> Chore/merge release v1.12

- .circleci/config.yml
- api/api_miner.go
- api/proxy_gen.go
- build/version.go
- docs/zh/CHANGELOG.md
- miner/api.go
- miner/miningmgr.go
- miner/multiminer.go
- node/impl/miner.go
- node/modules/slashfilter/api.go
- node/modules/slashfilter/local.go
- node/modules/slashfilter/slashfilter.go
- node/modules/slashfilter/slashfilter_test.go
- types/miner.go
> Chore/bump up version v1.12.1-rc1

- api/client/client.go
ref https://github.com/filecoin-project/venus/issues/5561
> feat: add  venus name space header

- miner/miningmgr.go
close https://github.com/filecoin-project/venus/issues/6083
> fix: add null round count

- node/config/def.go
> remove useless config code / 删除没用的配置代码

- build/version.go
- docs/zh/CHANGELOG.md
- node/builder.go
- node/config/def.go
- node/modules/mine-recorder/inner_recorder.go
close https://github.com/filecoin-project/venus/issues/6116
> feat: disable mine record by default

- miner/multiminer.go
> refactor: Only pass the information needed to computeTicket

- miner/miningmgr.go
- miner/util.go
close https://github.com/filecoin-project/venus/issues/6128
> feat: control concurrency when call CountWinner

- api/client/submitblock_client.go
- miner/multiminer.go
close https://github.com/filecoin-project/venus/issues/6160
> fix: get beacon earlier

- api/client/client.go
> opt: add DialMinerRPC

- api/docgen/example.go
- docs/en/api-v0-methods-miner.md
- miner/miner_test.go
- miner/miningmgr.go
- miner/multiminer.go
- types/miner.go
close https://github.com/filecoin-project/venus/issues/6226
> fix: return error message

- miner/multiminer.go
> fix: ignore lastWork when selecting the best mining candidate

- build/version.go
- go.mod
- go.sum
> chore: bump version to v1.18.0

- miner/multiminer.go
close
miner 和节点大量报错，但不影响出块
```
2025-04-09T13:18:22.697+0800    INFO    miner   miner/multiminer.go:467 no block and increase nullround
2025-04-09T13:18:26.910+0800    INFO    miner   miner/miningmgr.go:164  count winners, addrs: [f01984580], start: 4862160, end: 4862280
2025-04-09T13:18:33.003+0800    INFO    miner   miner/multiminer.go:497 try get beacon at: 4862319
2025-04-09T13:18:34.122+0800    INFO    miner   miner/multiminer.go:503 got beacon failed: drand failed Get request: no valid clients
got invalid status 425 doing GET request to "https://api3.drand.sh/52db9ba70e0cc0f6eaf7803dd07447a1f5477735fd3f661792ba94600c84e971/public/17124192"
got invalid status 404 doing GET request to "https://api.drand.secureweb3.com:6875/52db9ba70e0cc0f6eaf7803dd07447a1f5477735fd3f661792ba94600c84e971 …
```
> fix: not try get beacon
